### ISSUE TITLE
moar data when cashmaster is informed about new member

### ISSUE THREAD

**Issue by ghost** [shackspace/shackbureau#19]
Currently, the cashmaster gets:
- mandate date
- entry date
- mandate reference (wrong format, btw)
- iban

To improve copypasta and make things easier, I humbly request:
- mandate date
- entry date
- mandate reference: SHACKEVBEITRAGIDXXXX
- mandate reason: shack e.V. Mitgliedsbeitrag ID XXXX
- iban
- payment amount
- payment frequency

Thank you very much in advance.

**Comment by t2b** [comment]
most information is added.

payment amount and payment frequency are still missing
